name: Build and Release

on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PyQt5

    - name: Build App
      run: |
        pyinstaller --onefile Coratia_Streaming_App/main.py

    - name: Compress and Rename
      run: |
        tar -czvf csa_linux.tar.gz dist
        mv csa_linux.tar.gz csa_zip

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v2
      with:
        name: csa_zip
        path: csa_zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download Release Artifact
      uses: actions/download-artifact@v2
      with:
        name: csa_zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changes in this Release

    - name: Upload Release Artifact
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./csa_zip/csa_linux.tar.gz
        asset_name: csa_linux.tar.gz
        asset_content_type: application/gzip
